### ISSUE TITLE
board shape is wrong in firefox 123.0.1 (64-bit) Win11

### ISSUE THREAD

**Issue by Mrpapuj** [martinjakubik/knights#3]
![image](https://github.com/martinjakubik/knights/assets/163738120/f9ce1639-4386-4012-a20c-30dc6827360a)

**Comment by martinjakubik** [comment]
yeah it happens but I can't figure out under what conditions. Can you upload a photo of your computer screen taken with your phone? (not a screenshot, a photo)

**Comment by martinjakubik** [comment]
closing this as the fix seems to have worked
